example.http
API 테스트를 위한 HTTP 모의 요청 가능한 문서 작성
resolve #56 
- HTTP 요청을 vscode안에서 간단하게 모의 테스트 해볼 수 있게 작성하였습니다.
- [테스트 response 받는 법](https://www.codeit.kr/tutorials/37/REST-Client-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)
- [Rest Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) vscode 확장 플러그인 필요
=> #56 HTTP 모의 요청(REST client)

.eslintrc.js, package-lock.json, package.json, src/components/Button/Button.jsx, src/components/Button/Button.styles.js
close #60
공통컴포넌트 추가했습니다.
| **Prop**  | **Type**   | **Description** |
|-----------|------------|-----------------|
| `size`    | `string`   | s, m, l, xl |
| `color`   | `string`   | primary, secondary |
| `onClick` | `func`     | - |
| `disabled` | `boolean`  | (옵션) |
size, color, onClick 함수, disabled props들 정상적으로 받아서 작동되는지 확인완료
호버, 포커싱, 액티브 상태에 따른 변화 정상적인 작동 확인 완료
ex) 결과물에 대한 스크린 샷
1.
props으로 받는 type 속성과 to 속성을 추가하였습니다.
to 속성을 받을때는 Link 태그로 변경되고, 안받을때는 기본적으로 button 타입의 button 태그입니다.
Link 태그로 변경될떄는 일관된 스타일이 유지가 안되서 기본적인 스타일링을 추가하였습니다. 
Link 태그를 사용하기위해 react-router-dom 패키지를 설치하였습니다.
| **Prop**  | **Type**   | **Description** |
|-----------|------------|-----------------|
|`to` |`string` |라우터경로 ex) "/list"|
| `type`    | `string`   |submit, button, reset |
2. 
px로 작업된 폰트크기를 rem으로 변경하였습니다. …
=> #60 Feature/#60 공통컴포넌트   button

src/components/ArrowButton/ArrowButton.jsx, src/components/ArrowButton/ArrowButton.styles.js
close #84
롤링페이퍼 페이지에서 카드를 좌우로 넘기는 화살표버튼 컴포넌트입니다.
| Prop       | Type   | Description                                      |
|------------|--------|--------------------------------------------------|
| `direction` | string | `'left'` 또는 `'right'`를 받아 해당 방향의 화살표로 표시합니다. |
| `onClick`   | func   | - |
left, right에 따라 왼쪽, 오른쪽 두방향을 지원합니다.
클릭할떄 누르는것을 알수있도록 약간의 모션을 추가했습니다.
정상적으로 작동 되는것을 확인했습니다.
=> #84 ✨ 공통 컴포넌트 - ArrowButton 작업

src/styles/GlobalStyles.js
fix #105 
수치가 이상하게 들어간것같아서 재조정하고 모바일 media max-width가 잘못들어가있습니다
- 롤링 네임 기준 pc,태블릿,모바일 시안과 동일하게 적용됨 확인
=> #105 반응형 수치값 조정

src/components/Badge/Badge.jsx, src/components/Badge/Badge.styles.js
close #101
props으로 받은 value값에 해당하는 뱃지를 리턴합니다.
받을수 있는 값은 친구, 가족, 동료, 지인입니다.
| Prop  | type                           |desc|
|-------|----------------|-----|
| value | string |친구, 가족, 동료, 지인|
각 밸류값에 따라 정상적으로 뱃지가 출력되는것을 확인했습니다.
=> #101 ✨ 공통컴포넌트 - Badge 

src/components/TabToggle/TabToggle.jsx, src/components/TabToggle/TabToggle.styles.js
close #92
롤링페이퍼 생성페이지에서 사용되는 탭 토글메뉴입니다.
| Prop  | Type    | desc |
|-----------|---------|---------|
| `onClick`   | `func` | - |
| `tabs`      | `array[string]`  | - |
확장성을 고려해서 탭 항목을 배열로 받을수 있게 만들었습니다.
탭 메뉴 이동은 자체 스테이트로 관리되므로 
onClick을 통해서 현재 탭을 추적하고 추가적인 함수기능을 받아 수행할수 있어용.
탭토글 정상적으로 작동되는것 확인
=> #92 ✨ 공통컴포넌트 - TabToggle 작업

src/pages/MessagesList/MessagesHeader.jsx, src/pages/MessagesList/MessagesHeader.styles.js
close #110 
- 메세지 헤더 컴포넌트 입니다.
props | types | desc 
-- | -- | --
*name |string| '보낸이'  
badgeValue | oneOf | [친구,가족,동료,지인] 
profiler | shape | Profiler 컴포넌트에 전달할 props  
ㄴ*imageUrl | string | 유저 이미지 URL
ㄴsize | string | 유저 프로필 사이즈
createdAt | string | 생성 날짜
=> #110 유저 정보 컴포넌트

src/components/Button/Button.styles.js
close #125
- 색깔부분 기존 16진수에서 글로벌 변수로 변경하였습니다.
- width, height 같은 크기값 px -> rem 변경하였습니다.
- 폰트크기, 굵기를 글로별 변수로 변경하였습니다.
버튼 세컨더리 타입에서 hover, pressed 상태의 배경색깔과 포커스상태의 글씨색깔의 경우 
현재 변수값에 지정되지 않은 색깔이라 이 부분은 기존대로 놔두었습니다.
추후 해당 부분 변수값이 추가된다면 수정하겠습니다.
=> 💄버튼컴포넌트 스타일 변수식으로 변경

src/pages/RecipientsList/RecipientsList.jsx, src/utils/themeUtils.js
close #138 
기존에 복잡했던 테마 함수를 손쉽게 쓸 수 있습니다!
- 기존
`${({theme} => theme.colorTheme.blue[200])} `
- 유틸 함수 사용 시
`${tm_color('blue200')}`
- 기존
`${({theme}) => theme.fontTheme['20Regular']}`
- 유틸 함수 사용시
`${tm_font('20')}`
1. 폰트 함수(`tm_font`)
- 폰트는 폰트사이즈 입력하고 뒤에 아무것도 입력 안할경우 디폴트 값인 Regular로 자동적용 => ex : `${tm_font('20')}`
- 폰트사이즈 입력하고 b 입력 시 Bold => ex : `${tm_font('20b')}`
- 만약 테마에 없는 값일 경우 콘솔 에러 메시지 띄워줌
2. 컬러 함수(`tm_color`)
- 컬러는 정의된 네임과 숫자를 입력하면 적용됨 `${tm_color('blue300')}`
- 컬러 값이 아니더라도 hex로 입력해도 가능 `${tm_color('#9be282')}`
- 테마에 있는 고정값도 사용 가능 `${tm_color('white')}`
- 없는 색상도 괜찮아요! hex 코드가 그대로 적용! `color: ${tm_color('#374b5e')}` => `color: #374b5e` 로 적용됨
- 에러코드가 뜬 부분은 `${tm_font('2')}`, `${tm_font('100')}`
=> ✨ 테마 컬러와 폰트 쉽게 쓰는 유틸 함수 기능!

src/components/Outlined/Outlined.styles.js
close #136 
옵셔널 속성인 `iconPosition` 을 사용하지 않았는데 관련하여 아래와 같은 에러 문구가 발생함
```
hook.js:608 Warning: React does not recognize the `iconPosition` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `iconposition` instead. If you accidentally passed it from a parent component, remove it from the DOM element. Error Component Stack
```
---
- 정확한 스타일드컴포넌트의 규칙에 대해 미숙하여 생긴 버그입니다.
**아래는 이번 버그 발생에 대한 내용을 글로 정리하였습니다.**
동기적인 스타일링을 위해 스타일드컴포넌트에 변수를 전달하고 그 변수명을 그대로 받아서 사용하였는데,
스타일드컴포넌트에서 사용할때 변수명에 $를 붙이지 않고 그대로 사용하여 생긴 버그입니다.
해당 버그에 대해 알아보니
스타일드 컴포넌트가 받은 prop에 대해서 $를 붙이면 자체적으로 CSS 처리에만 사용되고, 
DOM에는 전달하지 않도록 라이브러리가 특별처리를 해준다고 합니다.
하지만 변수명에 $를 붙이지 않고 그냥 사용하게 되면 DOM 엘리먼트에 전달하게 되고,
스타일 컴포넌트도 컴포넌트이기 떄문에 하위 컴포넌트로 해당 속성이 전파될 수 있다고 합니다.
즉, 버튼 태그를 예로 …
=> #136 Outlined 컴포넌트의 스타일컴포넌트 변수사용시 $ 누락문제 수정

src/components/InputFile/InputFile.jsx, src/components/InputFile/InputFile.styles.js, src/components/Profile/Profile.jsx, src/components/Profile/Profile.styles.js, src/components/TextField/CommonInput.styles.js, src/components/TextField/Dropdown.jsx, src/components/TextField/Dropdown.styles.js, src/components/TextField/Input.jsx, src/components/TextField/TextField.jsx, src/components/TextField/TextField.styles.js, src/pages/MessagesAdd/MessagesAddPage.jsx, src/pages/MessagesAdd/MessagesAddPage.styles.js
close #163
1. dropdown, Input 부분의 props를 객체화하여 코드의 가독성을 높이고자 했습니다. 
-> 코드에 설명 첨가 했습니다 :-) 
- dropdown과 관련하여 @hwiiron 께서 요청해주신 작업들 모두 완료했습니다! 
- 또 추가적으로 dropdown 외부 클릭시 dropdown이 접히도록 개발해두었습니다. 
2. 메세지 추가하기 컨테이너 작업을 반응형으로 만들어 두었습니다 
@Hogn-hyeonbin 나중에 메세지 수정하기 작업하실 때 `MessagesAddPage`참고하셔서 그대로 가져다 쓰시고 안에 함수만 수정하는 함수로 가져다가 쓰시면 될 것 같습니다 👍 
`PC`
`태블릿`
`모바일`
=> #163 메세지 작성하기 컨테이너 작업 

src/components/ArrowButton/ArrowButton.styles.js
close #191
리스트페이지 카드이동하는 화살표버튼 figma에 맞게 투명도와 블러적용
- 블러는 변수설정해논것 사용하였음
사진은 테스트를 위해 눈에 잘보이게 black으로 찍었고, 실제는 white로 맞게 잘 적용되었습니다.
=> #191 애로우버튼 블러,투명도 적용

src/components/MessagesCardList/MessageCardList.jsx, src/components/TextField/TextEditor.jsx, src/pages/MessagesAdd/MessagesAddPage.jsx
close #196 
- `/post/롤링페이퍼 id/edit`에서 수정 버튼 클릭하면 해당하는 메시지 수정페이지로 이동하며, 생성 페이지를 재사용합니다
- 메시지의 id인 쿼리 파라미터를 저장하고, 데이터 요청을 하여 해당 메시지 데이터를 받아서 화면에 노출시킵니다.
- 수정하기 버튼을 클릭하면 PATCH 데이터 요청으로 메시지 데이터가 수정되고, 해당 롤링페이퍼로 이동하게 됩니다.
- 로딩 추가하였습니다.
=> #196 수정하기 페이지 기능 구현

src/pages/HomePage/HomePage.jsx
홈페이지 불러와지지 못하는 버그 잡기
close #228 
- 홈페이지를 제대로 불러오지 못해 급히 판 이슈였습니당 !
=> 🐛 홈페이지 불러와지지 못하는 버그 잡기

.env, src/components/CardComponents/CardList/CardList.jsx, src/pages/MessagesEdit/MessagesEditPage.jsx
close #220 
메시지 리스트 페이지에서 관리자모드 버튼 클릭 시 검증 후, 수정페이지로 이동하는 로직 추가하였습니다.
비밀번호의 경우 제 임의대로 정한 것이므로, 필요 시 수정하셔도 됩니다.
비밀번호 확인은 `.env` 파일에서 직접 확인 부탁드립니다!
=> #220 관리자 모드 버튼 패스워드로 edit로 이동

src/components/Button/Button.jsx, src/components/LoadingSpinner/LoadingSpinner.jsx, src/components/LoadingSpinner/LoadingSpinner.module.css, src/layout/Emoji/EmojiDropDown.jsx
close #246 
- Button 컴포넌트에 loading props가 추가되었습니다.
| prop | type | desc |
| ------- | ------- | ------- |
| `loading`    | `bool`| 로딩표시 유무 |
로딩값으로 true를 받으면 현재 버튼의 children 대신 로딩스피너를 보여줍니다.
- LoadingSpinner 컴포넌트가 추가되었습니다.
로딩스피너의 크기는 버튼의 세로길이 기준으로 변화하도록 설정하였습니다.
=> #246 ✨ 버튼 로딩스피너 추가

src/components/TextField/CommonInput.styles.js, src/components/TextField/Dropdown.jsx, src/components/TextField/Dropdown.module.css, src/components/TextField/Dropdown.styles.js
드롭다운 레이아웃 수정하기
close #262 
- 기존의 아이콘 드롭다운이 오른쪽 그림처럼 버튼의 왼쪽 모서리에 맞춰 드롭다운이 된 점을 왼쪽 그림 처럼 오른쪽 모서리에 맞춰 드롭다운 되도록 수정했습니다. 
- 아이콘 드롭다운 
- 기본 드롭다운도 문제 없습니당.
=> 💄 드롭다운 레이아웃 수정하기

src/components/BackgroundSelector/RadioCard.module.css, src/components/BackgroundSelector/RadioCard.styles.js
close #272 
모바일 해상도에서의 반응형 작업이 누락되어, 추가하였습니다.
수정 부분은 탭 안의 컬러, 이미지 버튼 수정하였습니다.
=> #272 롤링 페이퍼 생성 페이지 반응형 작업

src/components/CardComponents/CardAdd/CardAdd.styles.js
close #294 
메시지 리스트 페이지에서 메시지 생성 페이지로 이동하는 버튼이 `a`태그로 되어 있어, `Link` 태그로 변경하였습니다.
정상적으로 이동하는 것 확인했습니다.
=> #294 메시지 생성 페이지 이동 버튼 클릭 안됨 수정

src/pages/MessagesAdd/MessagesAddPage.module.css
close #293 
태블릿, 모바일 해상도
롤링 페이퍼 생성 페이지, 메시지 생성, 수정 페이지의 버튼 `position: fixed` 적용하였습니다.
=> #293 생성하기 수정하기 버튼 모바일에서 position
