codeit-sprint-part2-2team/rolling

- .eslintrc.js
- .vscode/settings.json
- package-lock.json
- package.json
> [#7] 포멧터 & 패키지 업데이트

- .github/workflows/create-branch.vml
#9 
github 워크플로우를 통해 이슈 생성 시 브랜치 자동 생성
> [#9] github 브랜치 네임 자동 생성

- README.md
> #29 리드미 배포 내용 추가

- README.md
close #32 
프로젝트 화면구성 내용 작성
- 테스트를 위해 텍스트를 추가했습니다.
> #32 리드미 테스트

- package-lock.json
- package.json
close #53 
오류 해결을 위해 패키지에 stylelint 추가 합니다.
> #53 stylelint 패키지 추가

- README.md
롤링 로고 추가, 개인 GitHub 계정 연결
close #58 
README 파일 최상단 로고 변경 및 개인 GitHub 계정 연결했습니다.
로고 잘 노출되는지 확인 후, PR 올립니다.
> 📝 README.md 수정

- .env
- src/hooks/README.md
- src/hooks/useApiAction.js
- src/hooks/useFetchData.js
- src/pages/rollingList/Test.jsx
- src/service/api.js
close #62 
- 해당 API 요청에 대한 공통 함수 api 작성했습니다
> API 요청 주소는 보안을 위해 별도의 파일로 분리했습니다. (프로젝트 완료 시 github 레포지토리에서 .env 삭제 예정)
- API 응답 함수도 커스텀 훅으로 작업하려했으나 렌더링 순서에 의해 데이터를 불러올때 옵셔널 체이닝을 활용하여, 기본값을 지정해주어야합니다. 아직 테스트 중인 코드이며, 작업하실때는 일반적으로 해당 컴포넌트에 API 응답 함수를 작성하여 사용하세요.
> GET을 제외하고, 나머지 메서드는 테스트하지 않았습니다. 기능 담당자 별로 테스트 부탁드려요
> #62 http 요청 함수

- src/pages/rollingList/Test.jsx
- src/service/api.js
fix #67 
- api 파일 delete 함수 '/' 누락으로 인한 버그 수정
> #67 http 요청 함수 버그 수정

- src/hooks/useInputValidation.js
- src/pages/MessagesAdd/MessagesAddPage.jsx
close #81 
텍스트 필드 유효성 검사 커스텀 훅으로 입력, 포커스 아웃 시 동작하는 함수로 구현되었습니다.
해당 기능을 구현하면서 다른 조건(특수문자, 숫자)으로도 검사를 진행하는 로직을 추가할지 고민이었는데,
현재 에러 메시지가 '값을 입력해 주세요.'로 한 가지 조건에만 성립하는 메시지로 되어 있으므로,
이 부분은 추가 개발 일정에 진행하는 것이 좋을 것 같아서 우선 요구 사항에 맞게 작업 하였습니다.
정상 동작
숫자 입력 시
특수문자 입력 시
2글자 미만
6글자 초과
미입력
> #81 ✨ 텍스트필드 유효성 검사 커스텀 훅 기능 구현

- package-lock.json
- package.json
- src/components/Badge/EmojiBadge.jsx
- src/components/Badge/EmojiBadge.styles.js
- src/components/Badge/EmojiBadgeTest.jsx
- src/pages/HomePage/HomePage.jsx
close #100 
- 이모지 배지 컴포넌트 구현 완료
- 이모지 피커 라이브러리랑 같이 테스트 완료
> Feature/#100 공통 컴포넌트   emoji badge

- src/hooks/useDeviceType.js
close #107 
|return | type | desc|
|-----|---|---|
|`'pc'/'tablet'/'mobile'` | string | 해당 훅을 호출하여, 변수에 조건을 담아 bool으로 컨트롤 가능|
> #107 디바이스 타입 감지 커스텀 훅

- src/utils/dateConversion.js
close #112
- 유저가 메세지를 생성한 날짜를 변환해주는 유틸 함수 입니다.
> 년.월.일 표기 오타로 인해 수정했으나 커밋 실수로인해 내용이 사라졌어요 ㅜㅜ
> #112 생성일 날짜 변환 유틸리티 함수

- src/hooks/useDeviceType.js
- 의존성 배열 추가
- useCallback 추가
fix #122 
- 터미널 에러가떠서 누락된 의존성 배열을 추가했습니다
- useCallback을 추가 했습니다.
> #122 디바이스 감지 훅 터미널 에러 수정

- src/components/InputFile/InputFile.jsx
- src/components/InputFile/InputFile.styles.js
- src/service/api.js
프로필 선택 기능 구현, 원하는 이미지 클릭 시 좌측 큰 이미지 변경되고 데이터 저장
close #114 
프로필 이미지 선택 시 좌측의 큰 이미지로 변경되고, 선택된 이미지의 데이터를 부모 컴포넌트로 리턴하여 상태를 업데이트 합니다.
> ✨ 프로필 이미지 선택 기능

- src/pages/MessagesList/MessagesHeader.jsx
fix #120 
해당 컴포넌트는 날짜 표시 여부에 대한 props를 받아야하는데 해당 부분 누락이 되어서 수정합니다
> 🔨 메세지 헤더 날짜 표시 노출 여부

- src/components/Badge/EmojiBadge.jsx
- src/components/Badge/EmojiBadge.styles.js
- src/pages/RecipientsList/RecipientsCard.jsx
- src/router/Content.jsx
resolve #147 
- 기존 롤링 카드 이모지 컴포넌트 연결 완료했습니다!
- 추가적으로 이모지 컴포넌트 스타일 디테일하게 수정 했습니다 @mangmang1004 확인해주세용
> #147 롤링 카드 이모지 라벨 연결

- src/pages/RecipientsList/RecipientsList.jsx
- src/pages/RecipientsList/RecipientsListPage.jsx
close #171 
| prop |  type | desc |
|---|---|---|
| ~~favorite~~ | ~~bool~~ |  |
| type | oneOf | favorite,recent |
- [ x ] 정상동작 확인 완료
> #171 멘토링 수정 사항반영

- .cspell.json
- src/components/MessagesCardList/MessageCard.jsx
- src/components/MessagesCardList/MessageCard.styles.js
- src/styles/GlobalStyles.js
close #190 
데이터에서 font값 가져와 SC으로 뿌려줬습니다!
그러면 이렇게 짜쨘 ✨
> #190 롤링 생성은 완료했으나 폰트로 적용되지않는 이슈

- .cspell.json
- src/App.jsx
- src/components/Badge/EmojiBadge.jsx
- src/components/Badge/EmojiBadge.styles.js
- src/layout/Emoji/EmojiPickerComponent.jsx
- src/layout/Emoji/EmojiPickerComponent.module.css
- src/layout/Emoji/useEmojiManager.js
- src/pages/MessagesList/MessagesListPage.jsx
- src/service/api.js
close #205 
- 기존에 용철님께서 만들어두신 상태를 인용해서, 이모지 삭제,추가,업데이트 기능을 구현하였습니다
- 삭제와 추가 모두 POST로 요청하기때문에 커스텀 훅으로 만들어 상태를 공유합니다
- 처음에 삭제가 POST 요청 인 줄 모르고 계속 DELETE로 요청하다가...이것때문에 시간이 좀 걸렸습니다
- 헤더 부분 완료되면 연결해주시면 되고 이모지 드롭다운 완료되면 해당 작업에 끼워넣고 추가적으로 드롭다운 컨텐츠 안에
노출되는 이모지의 갯수 기능도 추가 작업하겠습니다!! 
/post/{id} 페이지에서 확인가능합니다
> #205 이모지 클릭 시 해당 id 데이터에 삭제,추가,업데이트 진행

- src/pages/MessagesAdd/MessagesAddPage.jsx
- src/pages/MessagesAdd/MessagesAddPage.module.css
- src/pages/MessagesAdd/MessagesAddPage.styles.js
- src/pages/RecipientsAdd/RecipientsAddPage.jsx
close #197 
정적 스타일 컴포넌트 코드들을 모듈 CSS로 전환하기 위해 코드 수정하였습니다.
> #197 pages messages add메세지 생성

- src/pages/RecipientsList/RecipientsListPage.jsx
close #'224'
RecipientsListPage.jsx 파일에서 인기순, 최신순 롤링 페이퍼 type을 추가, 수정 했습니다
> 🐛 인기순,최신순 에러 수정 코드

- src/components/MessagesCardList/MessageCardList.jsx
close #235 
- 롤링 삭제 기능이 누락되어 작업했습니다
- 추가 스타일링 작업이 필요합니다.
> ✨ 롤링 삭제 누락되어 추가

- src/components/CardComponents/CardList/CardList.styles.js
- src/layout/Emoji/EmojiDropDown.jsx
- src/layout/Header/MainHeader.styles.js
- src/pages/MessagesEdit/MessagesEditPage.jsx
- src/pages/MessagesList/MessagesListPage.jsx
close #249 
- z-index 추가하여 이슈 수정
> Feature/#249 edit 이동 시 bg에 header 묻힘

- src/components/CardComponents/Card/Card.styles.js
- src/components/CardComponents/Card/CardBase.jsx
- src/components/CardComponents/Card/CardBase.styles.js
- src/components/CardComponents/Card/CustomCard.jsx
- src/components/CardComponents/CardContent/CardContent.jsx
- src/components/CardComponents/CardContent/CardContent.styles.js
- src/components/CardComponents/CardHeader/CardHeader.styles.js
- src/components/TextField/Dropdown.jsx
- src/components/TextField/Dropdown.styles.js
- src/pages/HomePage/Demo.jsx
- src/router/Content.jsx
- src/styles/common/Common.styles.js
- src/styles/common/media.styles.js
#259 
- 디자인 시스템 size, view props로 넣어서 사용하는 함수 Common.styles.js에 있습니다 가져다쓰세요
- 추후 첨부
> #242_모달,카드 & 디자인 시스템 작업

- src/components/NotfoundButton/BackButton.jsx
- src/pages/NotFound/NotFoundPage.jsx
- src/pages/NotFound/NotFoundPage.styles.js
close #244 
NotFoundPage
이상 없음
뒤로가기 기능을 useNavigate를 사용해서 구현 할려 했지만 react훅은 클래스 컴포넌트 내에서 사용이 불가능하다 해서  window.history.back()을 사용해서 구현했습니다.
> 에러 발생 시 화면 구현

- src/components/TotalMessage/TotalMessage.jsx
- src/components/TotalMessage/TotalMessage.styles.js
close #280 
다크모드에서 메시지 남긴 수 `n명이 작성했어요!` 부분 텍스트 화이트 적용
> Feature/#280 메시지 남긴 사람 수   다크모드

- src/components/NotfoundButton/BackButton.jsx
- src/pages/NotFound/NotFoundPage.jsx
- src/pages/NotFound/NotFoundPage.styles.js
에러 페이지 추가 수정
close #'285'
다크 모드 적용
버튼 공용 버튼 컴포넌트로 수정
텍스트,버튼,svg 간격 조정
> ♻️ 에퍼 페이지 추가 수정

- src/components/TextField/Dropdown.styles.js
- src/layout/Emoji/EmojiPickerComponent.jsx
이모지 드롭다운 hover width 간격 조정
close #302 
ex) 결과물에 대한 스크린 샷
> 💄 이모지 드롭다운 hover width 간격 조정

- src/components/CardComponents/CardList/CardList.jsx
close #304 
모바일에서 관리자 모드 오류 수정
> 🐛 모바일에서 관리자모드 오류 수정

- .github/workflows/jekyll-gh-pages.yml
- src/layout/Emoji/KaKaoShare.js
close #307 
커스텀된 템플릿이 공유되게 했습니다.
> kakao템플릿커스텀
